<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="NUnit" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
    <ProjectReference Include="../../src/HouseholdLedger.Client/HouseholdLedger.Client.csproj" />
  </ItemGroup>
</Project>
