<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageReference Include="xunit.v3.mtp-off" PrivateAssets="all" />
    <ProjectReference Include="../../src/HouseholdLedger.Client/HouseholdLedger.Client.csproj" />
  </ItemGroup>
</Project>
