<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <ProjectReference Include="../HouseholdLedger.Api.Contracts/HouseholdLedger.Api.Contracts.csproj" />
  </ItemGroup>
</Project>
