<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" PrivateAssets="all" />
    <PackageReference Include="NUnit" PrivateAssets="all" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
    <ProjectReference Include="../../src/HouseholdLedger.Api.Contracts/HouseholdLedger.Api.Contracts.csproj" />
  </ItemGroup>
</Project>
