// <auto-generated />
using System;
using HouseholdLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseholdLedger.Infrastructure.Migrations
{
    [DbContext(typeof(HouseholdLedgerDbContext))]
    [Migration("20260913042440_AddIncomeSchedules")]
    partial class AddIncomeSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseholdLedger.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_normalized_name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Settings.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("display_currency");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.ToTable("global_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_global_settings_display_currency", "display_currency IN ('USD', 'CAD', 'EUR', 'GBP', 'AUD', 'XXX')");

                            t.HasCheckConstraint("ck_global_settings_singleton", "id = 1");

                            t.HasCheckConstraint("ck_global_settings_theme", "theme IN ('workbench-dark', 'workbench-light')");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Transactions.ExpenseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("ledger_date");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("creation_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("Date", "Sequence");

                    b.ToTable("expense_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_transactions_amount_maximum", "amount <= 9999999999999999.99");

                            t.HasCheckConstraint("ck_expense_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_expense_transactions_amount_scale", "amount = round(amount, 2)");

                            t.HasCheckConstraint("ck_expense_transactions_classification", "classification IN ('Necessities', 'Optional', 'Culture', 'Unexpected')");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptAllocationRecord", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.HasKey("ReceiptId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReceiptId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_income_receipt_allocations_receipt_id_account_id");

                    b.ToTable("income_receipt_allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_income_receipt_allocations_amount_maximum", "amount <= 9999999999999999.99");

                            t.HasCheckConstraint("ck_income_receipt_allocations_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_income_receipt_allocations_amount_scale", "amount = round(amount, 2)");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("net_income");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("date")
                        .HasColumnName("pay_date");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "PayDate")
                        .IsUnique()
                        .HasDatabaseName("ux_income_receipts_schedule_id_pay_date");

                    b.ToTable("income_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_income_receipts_net_income_maximum", "net_income <= 9999999999999999.99");

                            t.HasCheckConstraint("ck_income_receipts_net_income_positive", "net_income > 0");

                            t.HasCheckConstraint("ck_income_receipts_net_income_scale", "net_income = round(net_income, 2)");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeScheduleAllocationRecord", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.HasKey("ScheduleId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("ScheduleId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_income_schedule_allocations_schedule_id_account_id");

                    b.ToTable("income_schedule_allocations", null, t =>
                        {
                            t.HasCheckConstraint("ck_income_schedule_allocations_amount_maximum", "amount <= 9999999999999999.99");

                            t.HasCheckConstraint("ck_income_schedule_allocations_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_income_schedule_allocations_amount_scale", "amount = round(amount, 2)");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.PayScheduleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cadence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cadence");

                    b.Property<DateOnly>("FirstPayDate")
                        .HasColumnType("date")
                        .HasColumnName("first_pay_date");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("net_income");

                    b.Property<DateOnly>("ReceiptEligibleFrom")
                        .HasColumnType("date")
                        .HasColumnName("receipt_eligible_from");

                    b.Property<int?>("SecondMonthlyPayDay")
                        .HasColumnType("integer")
                        .HasColumnName("second_monthly_pay_day");

                    b.HasKey("Id");

                    b.ToTable("pay_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_pay_schedules_cadence", "cadence IN ('Weekly', 'Biweekly', 'Semimonthly', 'FourWeekly', 'Monthly')");

                            t.HasCheckConstraint("ck_pay_schedules_net_income_maximum", "net_income <= 9999999999999999.99");

                            t.HasCheckConstraint("ck_pay_schedules_net_income_positive", "net_income > 0");

                            t.HasCheckConstraint("ck_pay_schedules_net_income_scale", "net_income = round(net_income, 2)");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Transactions.ExpenseTransaction", b =>
                {
                    b.HasOne("HouseholdLedger.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptAllocationRecord", b =>
                {
                    b.HasOne("HouseholdLedger.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptRecord", null)
                        .WithMany("Allocations")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptRecord", b =>
                {
                    b.HasOne("HouseholdLedger.Infrastructure.Persistence.PayScheduleRecord", null)
                        .WithMany("Receipts")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeScheduleAllocationRecord", b =>
                {
                    b.HasOne("HouseholdLedger.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HouseholdLedger.Infrastructure.Persistence.PayScheduleRecord", null)
                        .WithMany("Allocations")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.IncomeReceiptRecord", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("HouseholdLedger.Infrastructure.Persistence.PayScheduleRecord", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
