// <auto-generated />
using System;
using HouseholdLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseholdLedger.Infrastructure.Migrations
{
    [DbContext(typeof(HouseholdLedgerDbContext))]
    [Migration("20260906142223_AddGenericMoneyDisplay")]
    partial class AddGenericMoneyDisplay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseholdLedger.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_normalized_name");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Settings.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("display_currency");

                    b.HasKey("Id");

                    b.ToTable("global_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_global_settings_display_currency", "display_currency IN ('USD', 'CAD', 'EUR', 'GBP', 'AUD', 'XXX')");

                            t.HasCheckConstraint("ck_global_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Transactions.ExpenseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("ledger_date");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("creation_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Sequence")
                        .IsUnique();

                    b.HasIndex("Date", "Sequence");

                    b.ToTable("expense_transactions", (string)null);
                });

            modelBuilder.Entity("HouseholdLedger.Domain.Transactions.ExpenseTransaction", b =>
                {
                    b.HasOne("HouseholdLedger.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
